language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - composer test -- --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
